# Generated by Django 2.0 on 2020-03-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200317_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_data',
            name='current_money',
            field=models.IntegerField(default=0),
        ),
    ]
