# Generated by Django 3.0.4 on 2020-03-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20200329_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_data',
            name='cover',
            field=models.ImageField(default=None, upload_to='project_images'),
            preserve_default=False,
        ),
    ]
