# Generated by Django 3.0.4 on 2020-03-31 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_data_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_tags',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='project.Project_data'),
        ),
    ]
