# Generated by Django 2.0 on 2020-03-31 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_data_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_comment_replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project_comments')),
            ],
        ),
    ]
