# Generated by Django 2.0 on 2020-03-31 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_comment_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_comment_replies',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='project.project_comments'),
        ),
    ]
