# Generated by Django 3.0.4 on 2020-03-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20200331_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_data',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
