# Generated by Django 3.0.4 on 2020-04-02 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_project'),
        ('project', '0009_auto_20200331_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_comment_replies',
            name='reply_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reply_user', to='user.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project_comments',
            name='comment_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='user.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project_data',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project_comments',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='project.Project_data'),
        ),
        migrations.AlterField(
            model_name='project_pics',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.Project_data'),
        ),
        migrations.AlterField(
            model_name='project_tags',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='project.Project_data'),
        ),
    ]
