# Generated by Django 3.0.4 on 2020-04-02 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_project'),
        ('project', '0010_auto_20200402_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_project', to='project.Project_data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_user', to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Rate_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_project', to='project.Project_data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_user', to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Donate_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated_project', to='project.Project_data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donate_user', to='user.User')),
            ],
        ),
    ]
