# Generated by Django 3.0.4 on 2020-04-02 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_project'),
        ('project', '0011_donate_project_rate_project_report_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='report_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_id', to='project.project_comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_comment_user', to='user.User')),
            ],
        ),
    ]
