# Generated by Django 3.0.4 on 2020-04-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_report_comment'),
        ('project', '0009_project_data_featured'),
    ]

    operations = [
    ]
