# Generated by Django 3.0.4 on 2020-04-01 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_project_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
