# Generated by Django 3.0.4 on 2020-04-02 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_delete_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
