# Generated by Django 3.0.4 on 2020-03-30 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(max_length=100)),
                ('user_email_address', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=250)),
                ('sign_up_date', models.DateTimeField(auto_now_add=True)),
                ('verification_code', models.IntegerField()),
                ('is_verified_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('project_target', models.IntegerField()),
                ('donation_amount', models.IntegerField()),
                ('donations', models.ManyToManyField(related_name='donations', to='user.User')),
                ('project_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
