# Generated by Django 3.0.4 on 2020-04-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200402_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_birthDate',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='user',
            name='user_country',
            field=models.CharField( max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_phone',
            field=models.CharField( max_length=20),
        ),
    ]
