# Generated by Django 3.0.4 on 2020-04-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200403_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_birthDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.CharField(max_length=20),
        ),
    ]
