# Generated by Django 3.0.4 on 2020-04-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200403_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_birthDate',
            field=models.DateField(null=True),
        ),
    ]
