# Generated by Django 3.0.4 on 2020-04-03 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200403_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_phone',
            new_name='user_phone_number',
        ),
    ]
