# Generated by Django 3.0.4 on 2020-04-03 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_merge_20200402_2043'),
        ('user', '0007_auto_20200403_1833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
