# Generated by Django 3.0.4 on 2020-04-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_profile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
