# Generated by Django 3.0.4 on 2020-04-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200404_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_birthDate',
            field=models.DateField(null=True),
        ),
    ]
