# Generated by Django 2.1.5 on 2020-03-30 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user-profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
